version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - TAKE_FILE_OWNERSHIP=true
      - ELASTIC_PASSWORD=YourElasticPassword
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.http.ssl.verification_mode=none
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/http.p12:/usr/share/elasticsearch/config/http.p12

  kibana:
    image: kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=YourElasticPassword
    ports:
      - "5601:5601"

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: logs-server
    image: logs-server:v0.0.1
    volumes:
      - ./apps/server:/usr/src/app/apps/server
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch

  cli:
    build:
      context: .
      dockerfile: apps/cli/Dockerfile
    container_name: logs-cli
    image: logs-cli:v0.0.1
    depends_on:
      - elasticsearch
    volumes:
      - ./apps/cli:/usr/src/app/apps/cli

volumes:
  esdata:
    driver: local
